name: 🧩 Create Issue
description: 새로운 이슈를 등록합니다.
title: "[Feature] "
labels: ["자동 생성"]

body:
  - type: dropdown
    id: branch-type
    attributes:
      label: 브랜치 타입 선택
      description: 생성될 브랜치 prefix를 선택하세요.
      options:
        - feature
        - fix
        - build
        - docs
        - refactor
        - style
        - chore
    validations:
      required: true

  - type: input
    id: summary
    attributes:
      label: 작업 요약 (영문으로 작성 시 브랜치명에 그대로 반영됩니다)
      placeholder: "예: dashboard cpu chart 추가"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 상세 내용
      description: 작업의 목적, 변경 사항 등을 자세히 작성해주세요.
      placeholder: |
        - 목적:
        - 변경 사항:
        - 참고 링크:
    validations:
      required: true
