name: Feature Request
description: Request a new feature
body:
  - type: input
    id: parentKey
    attributes:
      label: Parent Epic Key
      placeholder: "SKP-123"
  - type: input
    id: branch
    attributes:
      label: Branch Name
      placeholder: "feature-name"
  - type: textarea
    id: description
    attributes:
      label: Description
