export type DatabaseMetricsAgg = {
  instanceId: number;
  databaseId: number;
  collectedAt: string;
  activeSessions: number;
  usedConnections: number;
  maxConnections: number;
  connectionUsagePercent: number;
  tpsTotal: number;
  xactCommit: number;
  xactRollback: number;
  lockWaitCount: number;
  ioWaitCount: number;
  blksHit: number;
  blksRead: number;
  cacheHitRatio: number;
  avgReadLatencyMs: number;
  avgWriteLatencyMs: number;
  slowQueryCount: number;
  topSlowQuery1?: string | null;
  topSlowQuery1Time?: number | null;
  topSlowQuery2?: string | null;
  topSlowQuery2Time?: number | null;
  topSlowQuery3?: string | null;
  topSlowQuery3Time?: number | null;
  deadTupleTotal: number;
  infoEventCount: number;
  warningEventCount: number;
  criticalEventCount: number;
  recentEventType?: string | null;
  recentEventLevel?: string | null;
  recentEventAgeMin?: number | null;
  createdAt?: string;
};
